# Generated by Django 5.0.1 on 2024-11-03 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeanalysis',
            options={},
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume_file',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
